name: CI

on:
  - push
  - pull_request

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version }}

      - name: Install-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest 
          python -m pip install pytest-cov
          python -m pip install PyQt6 
          python -m pip install clipboard 
          python -m pip install PyCryptodome
          python -m pip install pytest 

      - name: Run test
        run: pytest --cov
